"""Add FundTable

Revision ID: 0eb3b9a6876e
Revises: 
Create Date: 2026-07-20 20:54:59.002346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb3b9a6876e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('risk_profile', sa.String(), nullable=True),
    sa.Column('asisa_classification', sa.String(), nullable=True),
    sa.Column('benchmark', sa.String(), nullable=True),
    sa.Column('portfolio_launch_date', sa.Date(), nullable=True),
    sa.Column('portfolio_size', sa.String(), nullable=True),
    sa.Column('fund_hash', sa.String(length=64), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_fund_hash'), 'funds', ['fund_hash'], unique=False)
    op.create_index(op.f('ix_funds_manager'), 'funds', ['manager'], unique=False)
    op.create_index(op.f('ix_funds_name'), 'funds', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funds_name'), table_name='funds')
    op.drop_index(op.f('ix_funds_manager'), table_name='funds')
    op.drop_index(op.f('ix_funds_fund_hash'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
