"""Add AssetAllocationTable

Revision ID: 2b873ea10f58
Revises: 387214274789
Create Date: 2026-07-20 21:10:58.067625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b873ea10f58'
down_revision: Union[str, Sequence[str], None] = '387214274789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'asset_class', 'as_of_date', name='uq_asset_allocation_fund_class_date')
    )
    op.create_index(op.f('ix_asset_allocations_as_of_date'), 'asset_allocations', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_asset_allocations_fund_id'), 'asset_allocations', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_allocations_fund_id'), table_name='asset_allocations')
    op.drop_index(op.f('ix_asset_allocations_as_of_date'), table_name='asset_allocations')
    op.drop_table('asset_allocations')
    # ### end Alembic commands ###
