"""Add PerformanceRecordTable

Revision ID: 30a8b2ba00a1
Revises: 2b873ea10f58
Create Date: 2026-07-20 21:11:37.370054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a8b2ba00a1'
down_revision: Union[str, Sequence[str], None] = '2b873ea10f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('fund_return_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tracking_difference_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'period', 'as_of_date', name='uq_performance_fund_period_date')
    )
    op.create_index(op.f('ix_performance_records_as_of_date'), 'performance_records', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_performance_records_fund_id'), 'performance_records', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_records_fund_id'), table_name='performance_records')
    op.drop_index(op.f('ix_performance_records_as_of_date'), table_name='performance_records')
    op.drop_table('performance_records')
    # ### end Alembic commands ###
