"""Add FeeTable

Revision ID: 387214274789
Revises: dfcdc45041bc
Create Date: 2026-07-20 21:10:16.521636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387214274789'
down_revision: Union[str, Sequence[str], None] = 'dfcdc45041bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('advice_initial_fee_max_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('manager_initial_fee_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('advice_annual_fee_max_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('manager_annual_fee_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('ter', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('transaction_cost_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('total_investment_charge_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='ZAR', nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'effective_date', name='uq_fee_fund_effective_date')
    )
    op.create_index(op.f('ix_fees_effective_date'), 'fees', ['effective_date'], unique=False)
    op.create_index(op.f('ix_fees_fund_id'), 'fees', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fees_fund_id'), table_name='fees')
    op.drop_index(op.f('ix_fees_effective_date'), table_name='fees')
    op.drop_table('fees')
    # ### end Alembic commands ###
