"""Add AnnualReturnsTable

Revision ID: c1da68323fd4
Revises: 30a8b2ba00a1
Create Date: 2026-07-20 21:12:25.116431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1da68323fd4'
down_revision: Union[str, Sequence[str], None] = '30a8b2ba00a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_returns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('highest_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('lowest_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'as_of_date', name='uq_annual_returns_fund_date')
    )
    op.create_index(op.f('ix_annual_returns_as_of_date'), 'annual_returns', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_annual_returns_fund_id'), 'annual_returns', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annual_returns_fund_id'), table_name='annual_returns')
    op.drop_index(op.f('ix_annual_returns_as_of_date'), table_name='annual_returns')
    op.drop_table('annual_returns')
    # ### end Alembic commands ###
