"""Add HoldingTable

Revision ID: dfcdc45041bc
Revises: 0eb3b9a6876e
Create Date: 2026-07-20 21:06:47.558605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcdc45041bc'
down_revision: Union[str, Sequence[str], None] = '0eb3b9a6876e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('instrument_name', sa.String(), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'instrument_name', 'as_of_date', name='uq_holding_fund_instrument_date')
    )
    op.create_index(op.f('ix_holdings_as_of_date'), 'holdings', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_holdings_fund_id'), 'holdings', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_fund_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_as_of_date'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
