"""Add FundChunkTable

Revision ID: fc690c8d38cc
Revises: c1da68323fd4
Create Date: 2026-07-20 21:22:46.298551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'fc690c8d38cc'
down_revision: Union[str, Sequence[str], None] = 'c1da68323fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('fund_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('headings', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'content_hash', name='uq_fund_chunk_fund_content_hash')
    )
    op.create_index(op.f('ix_fund_chunks_fund_id'), 'fund_chunks', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_chunks_fund_id'), table_name='fund_chunks')
    op.drop_table('fund_chunks')
    # ### end Alembic commands ###
